/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import DAO.UsuarioDAO;
import javax.swing.JOptionPane;
import Modelo.Usuario;

/**
 *
 * @author Jonathan
 */
public class formLogin extends javax.swing.JFrame {

    /**
     * Creates new form formLogin
     */
    public formLogin() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panLogin = new javax.swing.JPanel();
        labUsuario = new javax.swing.JLabel();
        labPassword = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        labCopy = new javax.swing.JLabel();
        labTitle = new javax.swing.JLabel();
        labLoginImg = new javax.swing.JLabel();
        labMainIcon = new javax.swing.JLabel();
        sepUsuario = new javax.swing.JSeparator();
        sepPassword = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(".: SIFARM :.");
        setLocationByPlatform(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panLogin.setBackground(new java.awt.Color(30, 150, 210));

        labUsuario.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        labUsuario.setForeground(new java.awt.Color(255, 255, 255));
        labUsuario.setText("Usuario");

        labPassword.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        labPassword.setForeground(new java.awt.Color(255, 255, 255));
        labPassword.setText("Contraseña");

        txtUsuario.setBackground(new java.awt.Color(30, 150, 210));
        txtUsuario.setFont(new java.awt.Font("Roboto Light", 0, 22)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(255, 255, 255));
        txtUsuario.setBorder(null);

        txtPassword.setBackground(new java.awt.Color(30, 150, 210));
        txtPassword.setFont(new java.awt.Font("Roboto Light", 0, 22)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(255, 255, 255));
        txtPassword.setBorder(null);

        btnLogin.setBackground(new java.awt.Color(242, 193, 34));
        btnLogin.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Entrar");
        btnLogin.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnLogin.setMargin(new java.awt.Insets(7, 14, 7, 14));
        btnLogin.setMaximumSize(new java.awt.Dimension(48, 28));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        labCopy.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        labCopy.setForeground(new java.awt.Color(255, 255, 255));
        labCopy.setText("©2023 Elaborado y diseñado por 2 TDS");

        labTitle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labTitle.setForeground(new java.awt.Color(255, 255, 255));
        labTitle.setText("Iniciar Sesión");

        labLoginImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/general/fondologin.png"))); // NOI18N

        labMainIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/general/logosifar.png"))); // NOI18N

        sepUsuario.setBackground(new java.awt.Color(240, 240, 240));
        sepUsuario.setForeground(new java.awt.Color(255, 255, 255));

        sepPassword.setBackground(new java.awt.Color(240, 240, 240));
        sepPassword.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panLoginLayout = new javax.swing.GroupLayout(panLogin);
        panLogin.setLayout(panLoginLayout);
        panLoginLayout.setHorizontalGroup(
            panLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panLoginLayout.createSequentialGroup()
                .addGroup(panLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panLoginLayout.createSequentialGroup()
                        .addContainerGap(26, Short.MAX_VALUE)
                        .addGroup(panLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(sepPassword)
                            .addComponent(txtPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                            .addComponent(labUsuario, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sepUsuario)
                            .addGroup(panLoginLayout.createSequentialGroup()
                                .addComponent(labTitle)
                                .addGap(18, 18, 18)
                                .addComponent(labMainIcon))
                            .addComponent(txtUsuario)
                            .addComponent(labPassword, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(43, 43, 43))
                    .addGroup(panLoginLayout.createSequentialGroup()
                        .addGroup(panLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panLoginLayout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addComponent(labCopy))
                            .addGroup(panLoginLayout.createSequentialGroup()
                                .addGap(125, 125, 125)
                                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(labLoginImg)
                .addGap(1, 1, 1))
        );
        panLoginLayout.setVerticalGroup(
            panLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panLoginLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labMainIcon)
                    .addComponent(labTitle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labUsuario)
                .addGap(18, 18, 18)
                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sepUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(labPassword)
                .addGap(18, 18, 18)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sepPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(labCopy)
                .addContainerGap())
            .addComponent(labLoginImg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(panLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed

        String password = String.valueOf(txtPassword.getPassword());
        Usuario user = new Usuario();
        UsuarioDAO acc = new UsuarioDAO();

        if(!txtUsuario.getText().equals("") && !password.equals("")){

            user.setUsername(txtUsuario.getText());
            user.setPassword(password);

            if(acc.login(user)){
                //this.setVisible(false);
                this.dispose();
                formHome dashboard = new formHome(user);
                dashboard.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(null, "Usuario y/o contraseña incorrectos.");
            }

        }else{
            JOptionPane.showMessageDialog(null, "Usuario y/o contraseña incorrectos.");
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel labCopy;
    private javax.swing.JLabel labLoginImg;
    private javax.swing.JLabel labMainIcon;
    private javax.swing.JLabel labPassword;
    private javax.swing.JLabel labTitle;
    private javax.swing.JLabel labUsuario;
    private javax.swing.JPanel panLogin;
    private javax.swing.JSeparator sepPassword;
    private javax.swing.JSeparator sepUsuario;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
