/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import DAO.CategoriaDAO;
import DAO.ClienteDAO;
import DAO.MedidaDAO;
import DAO.ProductoDAO;
import Modelo.Categoria;
import Modelo.Cliente;
import Modelo.Iva;
import Modelo.Medida;
import Modelo.Producto;
import Modelo.Usuario;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author Jonathan
 */
public class formRegistroDetalleEntradaAdd extends javax.swing.JFrame {

    Usuario sysUser;
    /**
     * Creates new form formUsuarioAdd
     */
    public formRegistroDetalleEntradaAdd() {
        initComponents();
        this.setLocationRelativeTo(null);
        getLimiteCantidad();
        
        
        
    }


    public void getLimiteCantidad(){
        SpinnerNumberModel model = new SpinnerNumberModel();
        model.setMaximum(15);
        model.setMinimum(5);
        model.setStepSize(1);
        model.setValue(5);
        txtCantidad.setModel(model);
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panMain = new javax.swing.JPanel();
        labTitle = new javax.swing.JLabel();
        labRUC = new javax.swing.JLabel();
        txtIdProducto = new javax.swing.JTextField();
        labRazonSocial = new javax.swing.JLabel();
        txtNombreProducto = new javax.swing.JTextField();
        labMedida = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        txtTotal = new javax.swing.JTextField();
        labPorcentajeIva = new javax.swing.JLabel();
        labCodigo = new javax.swing.JLabel();
        labCategoria = new javax.swing.JLabel();
        txtCodigoEntrada = new javax.swing.JFormattedTextField();
        btnGuardar2 = new javax.swing.JButton();
        txtPrecio = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        txtIva = new javax.swing.JTextField();
        labMedida1 = new javax.swing.JLabel();
        labMedida2 = new javax.swing.JLabel();
        txtSubtotal = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        panMain.setBackground(new java.awt.Color(255, 255, 255));
        panMain.setForeground(new java.awt.Color(255, 255, 255));
        panMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labTitle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labTitle.setForeground(new java.awt.Color(11, 58, 82));
        labTitle.setText("Registrar Detalle de Entrada");
        panMain.add(labTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        labRUC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labRUC.setText("Código Entrada");
        panMain.add(labRUC, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, -1, -1));

        txtIdProducto.setEditable(false);
        txtIdProducto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtIdProducto.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtIdProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdProductoActionPerformed(evt);
            }
        });
        panMain.add(txtIdProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 130, 30));

        labRazonSocial.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labRazonSocial.setText("Nombre del Producto");
        panMain.add(labRazonSocial, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        txtNombreProducto.setEditable(false);
        txtNombreProducto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNombreProducto.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtNombreProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreProductoActionPerformed(evt);
            }
        });
        panMain.add(txtNombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 420, 30));

        labMedida.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labMedida.setText("Precio");
        panMain.add(labMedida, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, -1, -1));

        btnGuardar.setBackground(new java.awt.Color(204, 204, 204));
        btnGuardar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnGuardar.setText("Cancelar");
        btnGuardar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        panMain.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 440, 90, 30));

        txtTotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTotal.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });
        panMain.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 130, 30));

        labPorcentajeIva.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labPorcentajeIva.setText("Total");
        panMain.add(labPorcentajeIva, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        labCodigo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labCodigo.setText("Producto");
        panMain.add(labCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        labCategoria.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labCategoria.setText("Cantidad");
        panMain.add(labCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        txtCodigoEntrada.setEditable(false);
        txtCodigoEntrada.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        panMain.add(txtCodigoEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 130, 30));

        btnGuardar2.setBackground(new java.awt.Color(11, 58, 82));
        btnGuardar2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnGuardar2.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar2.setText("Guardar");
        btnGuardar2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnGuardar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar2ActionPerformed(evt);
            }
        });
        panMain.add(btnGuardar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, 90, 30));

        txtPrecio.setEditable(false);
        txtPrecio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPrecio.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioActionPerformed(evt);
            }
        });
        panMain.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 130, 30));

        btnBuscar.setBackground(new java.awt.Color(11, 58, 82));
        btnBuscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar");
        btnBuscar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        panMain.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 60, 30));

        txtIva.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtIva.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtIva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIvaActionPerformed(evt);
            }
        });
        panMain.add(txtIva, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 130, 30));

        labMedida1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labMedida1.setText("Iva");
        panMain.add(labMedida1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, -1, -1));

        labMedida2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labMedida2.setText("Subtotal");
        panMain.add(labMedida2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        txtSubtotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSubtotal.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtSubtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubtotalActionPerformed(evt);
            }
        });
        panMain.add(txtSubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 130, 30));

        txtCantidad.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                txtCantidadStateChanged(evt);
            }
        });
        panMain.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 232, 120, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panMain, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panMain, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreProductoActionPerformed

    private void txtIdProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdProductoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        
        this.dispose();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void btnGuardar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardar2ActionPerformed

    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        formBuscarProducto formBuscar = new formBuscarProducto();
        formBuscar.setVisible(true);
                
                
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtIvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIvaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIvaActionPerformed

    private void txtSubtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubtotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSubtotalActionPerformed

    private void txtCantidadStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_txtCantidadStateChanged
        
        int cantidad = (int) txtCantidad.getValue();
        String precio = txtPrecio.getText();
        float nprecio = Float.parseFloat(precio);
        float subtotal = nprecio * cantidad;
        txtSubtotal.setText(String.valueOf(subtotal));
        
        
    }//GEN-LAST:event_txtCantidadStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formRegistroDetalleEntradaAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formRegistroDetalleEntradaAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formRegistroDetalleEntradaAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formRegistroDetalleEntradaAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formRegistroDetalleEntradaAdd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnGuardar2;
    private javax.swing.JLabel labCategoria;
    private javax.swing.JLabel labCodigo;
    private javax.swing.JLabel labMedida;
    private javax.swing.JLabel labMedida1;
    private javax.swing.JLabel labMedida2;
    private javax.swing.JLabel labPorcentajeIva;
    private javax.swing.JLabel labRUC;
    private javax.swing.JLabel labRazonSocial;
    private javax.swing.JLabel labTitle;
    private javax.swing.JPanel panMain;
    private javax.swing.JSpinner txtCantidad;
    private javax.swing.JFormattedTextField txtCodigoEntrada;
    public static javax.swing.JTextField txtIdProducto;
    private javax.swing.JTextField txtIva;
    public static javax.swing.JTextField txtNombreProducto;
    public static javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtSubtotal;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
