/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import DAO.ClienteDAO;
import DAO.ProductoDAO;
import Modelo.Cliente;
import Modelo.Producto;
import Modelo.Usuario;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;

/**
 *
 * @author Jonathan
 */
public class formProductoEdit extends javax.swing.JFrame {

    Usuario sysUser;
    /**
     * Creates new form formUsuarioAdd
     */
    public formProductoEdit() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public formProductoEdit(String id, Usuario user) {
        initComponents();
        this.sysUser = user;
        this.setLocationRelativeTo(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panMain = new javax.swing.JPanel();
        labTitle = new javax.swing.JLabel();
        labRUC = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        labRazonSocial = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        labMedida = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        btnGuardar = new javax.swing.JButton();
        btnGuardar1 = new javax.swing.JButton();
        labPrecio = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        labPorcentajeIva = new javax.swing.JLabel();
        calFechaCaducidad = new com.toedter.calendar.JDateChooser();
        labCodigo = new javax.swing.JLabel();
        listPorcentajeIva = new javax.swing.JComboBox<>();
        listCategoria = new javax.swing.JComboBox<>();
        labDescripcion = new javax.swing.JLabel();
        labCategoria = new javax.swing.JLabel();
        listMedida = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        panMain.setBackground(new java.awt.Color(255, 255, 255));
        panMain.setForeground(new java.awt.Color(255, 255, 255));
        panMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labTitle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labTitle.setForeground(new java.awt.Color(11, 58, 82));
        labTitle.setText("Registrar Producto");
        panMain.add(labTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        labRUC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labRUC.setText("Fecha de caducidad");
        panMain.add(labRUC, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, -1, -1));

        txtCodigo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCodigo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });
        panMain.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 200, 30));

        labRazonSocial.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labRazonSocial.setText("Nombre");
        panMain.add(labRazonSocial, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        txtNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNombre.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        panMain.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 457, 30));

        labMedida.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labMedida.setText("Medida");
        panMain.add(labMedida, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, -1, -1));

        txtDescripcion.setColumns(20);
        txtDescripcion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDescripcion.setRows(5);
        txtDescripcion.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jScrollPane1.setViewportView(txtDescripcion);

        panMain.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 457, -1));

        btnGuardar.setBackground(new java.awt.Color(204, 204, 204));
        btnGuardar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnGuardar.setText("Cancelar");
        btnGuardar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        panMain.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 510, 90, 30));

        btnGuardar1.setBackground(new java.awt.Color(11, 58, 82));
        btnGuardar1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnGuardar1.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar1.setText("Guardar");
        btnGuardar1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnGuardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar1ActionPerformed(evt);
            }
        });
        panMain.add(btnGuardar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 510, 90, 30));

        labPrecio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labPrecio.setText("Precio");
        panMain.add(labPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, -1));

        txtPrecio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPrecio.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioActionPerformed(evt);
            }
        });
        panMain.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 200, 30));

        labPorcentajeIva.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labPorcentajeIva.setText("Porcentaje IVA");
        panMain.add(labPorcentajeIva, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, -1, -1));
        panMain.add(calFechaCaducidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 200, 30));

        labCodigo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labCodigo.setText("Código");
        panMain.add(labCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        listPorcentajeIva.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panMain.add(listPorcentajeIva, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 430, 200, 30));

        listCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panMain.add(listCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 200, 30));

        labDescripcion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labDescripcion.setText("Descripción");
        panMain.add(labDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        labCategoria.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labCategoria.setText("Categoría");
        panMain.add(labCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        listMedida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panMain.add(listMedida, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, 200, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panMain, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panMain, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        
        this.dispose();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnGuardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar1ActionPerformed
        
        Producto produ = new Producto();
        ProductoDAO produDAO = new ProductoDAO();
        
        if(!txtCodigo.getText().equals("") && !txtNombre.getText().equals("") && 
                !txtDescripcion.getText().equals("")){
            
            produ.setCodigo((String)txtCodigo.getText());
            produ.setNombre((String)txtNombre.getText());
            produ.setDescripcion((String)txtDescripcion.getText());
            produ.setPrecio(Float.parseFloat(txtPrecio.getText()));
            produ.setPorcentajeIva(listPorcentajeIva.getSelectedIndex());
            String fechaLocal= calFechaCaducidad.getDateFormatString();
            produ.setFechaCaducidad(LocalDate.parse(fechaLocal));
            produ.setIdCategoria(listPorcentajeIva.getSelectedIndex());
            produ.setIdMedida(listPorcentajeIva.getSelectedIndex());
            
                produ.setEstado(1);
                produ.setFechaIngreso(LocalDateTime.now());
                produ.setUsuarioIngreso(sysUser.getUsername());
                            
                if(produDAO.registrar(produ)){                           
                    this.dispose();
                    formClientes.getClientes();

                }else{
                    JOptionPane.showMessageDialog(null, "No se guradaron los datos.");
                }
                        
            
        }else{
            JOptionPane.showMessageDialog(null, "Por favor, complete todos los campos del formulario.");
        }
        
    }//GEN-LAST:event_btnGuardar1ActionPerformed

    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formProductoEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formProductoEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formProductoEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formProductoEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formProductoEdit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnGuardar1;
    private com.toedter.calendar.JDateChooser calFechaCaducidad;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labCategoria;
    private javax.swing.JLabel labCodigo;
    private javax.swing.JLabel labDescripcion;
    private javax.swing.JLabel labMedida;
    private javax.swing.JLabel labPorcentajeIva;
    private javax.swing.JLabel labPrecio;
    private javax.swing.JLabel labRUC;
    private javax.swing.JLabel labRazonSocial;
    private javax.swing.JLabel labTitle;
    private javax.swing.JComboBox<String> listCategoria;
    private javax.swing.JComboBox<String> listMedida;
    private javax.swing.JComboBox<String> listPorcentajeIva;
    private javax.swing.JPanel panMain;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
