/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import DAO.CategoriaDAO;
import DAO.ClienteDAO;
import DAO.MedidaDAO;
import DAO.ProductoDAO;
import Modelo.Categoria;
import Modelo.Cliente;
import Modelo.Iva;
import Modelo.Medida;
import Modelo.Producto;
import Modelo.Usuario;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Jonathan
 */
public class formRegistroEntradaAdd extends javax.swing.JFrame {

    Usuario sysUser;
    /**
     * Creates new form formUsuarioAdd
     */
    public formRegistroEntradaAdd() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public formRegistroEntradaAdd(Usuario user) {
        initComponents();
        this.sysUser = user;
        this.setLocationRelativeTo(null);
        
    }
    
    public formRegistroEntradaAdd(String id) {
        initComponents();
        this.txtIdProveedor.setText(id);
        this.setLocationRelativeTo(null);
        
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panMain = new javax.swing.JPanel();
        labTitle = new javax.swing.JLabel();
        labRUC = new javax.swing.JLabel();
        txtIdProveedor = new javax.swing.JTextField();
        labRazonSocial = new javax.swing.JLabel();
        txtRazonSocial = new javax.swing.JTextField();
        labMedida = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnAgregarProducto = new javax.swing.JButton();
        labPrecio = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        labPorcentajeIva = new javax.swing.JLabel();
        labCodigo = new javax.swing.JLabel();
        labDescripcion = new javax.swing.JLabel();
        labCategoria = new javax.swing.JLabel();
        txtFechaIngreso = new javax.swing.JFormattedTextField();
        btnGuardar = new javax.swing.JButton();
        txtDescuento = new javax.swing.JTextField();
        txtSubtotal = new javax.swing.JTextField();
        txtIva = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabProductos = new javax.swing.JTable();
        btnBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        panMain.setBackground(new java.awt.Color(255, 255, 255));
        panMain.setForeground(new java.awt.Color(255, 255, 255));
        panMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labTitle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labTitle.setForeground(new java.awt.Color(11, 58, 82));
        labTitle.setText("Registrar Entrada de Productos");
        panMain.add(labTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        labRUC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labRUC.setText("Fecha de Ingreso");
        panMain.add(labRUC, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, -1, -1));

        txtIdProveedor.setEditable(false);
        txtIdProveedor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtIdProveedor.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtIdProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdProveedorActionPerformed(evt);
            }
        });
        panMain.add(txtIdProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 130, 30));

        labRazonSocial.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labRazonSocial.setText("Razón Social");
        panMain.add(labRazonSocial, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        txtRazonSocial.setEditable(false);
        txtRazonSocial.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtRazonSocial.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtRazonSocial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRazonSocialActionPerformed(evt);
            }
        });
        panMain.add(txtRazonSocial, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 460, 30));

        labMedida.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labMedida.setText("Iva");
        panMain.add(labMedida, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 420, -1, -1));

        btnCancelar.setBackground(new java.awt.Color(204, 204, 204));
        btnCancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        panMain.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 590, 90, 30));

        btnAgregarProducto.setBackground(new java.awt.Color(11, 58, 82));
        btnAgregarProducto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAgregarProducto.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarProducto.setText("Agregar Producto");
        btnAgregarProducto.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProductoActionPerformed(evt);
            }
        });
        panMain.add(btnAgregarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 130, 30));

        labPrecio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labPrecio.setText("Descuento");
        panMain.add(labPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, -1, -1));

        txtTotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTotal.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });
        panMain.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 520, 130, 30));

        labPorcentajeIva.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labPorcentajeIva.setText("Total");
        panMain.add(labPorcentajeIva, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 500, -1, -1));

        labCodigo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labCodigo.setText("Proveedor");
        panMain.add(labCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        labDescripcion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labDescripcion.setText("Detalle");
        panMain.add(labDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        labCategoria.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labCategoria.setText("Subtotal");
        panMain.add(labCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, -1));

        txtFechaIngreso.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        txtFechaIngreso.setText("dd/MM/yyyy");
        panMain.add(txtFechaIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 170, 30));

        btnGuardar.setBackground(new java.awt.Color(11, 58, 82));
        btnGuardar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        panMain.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 590, 90, 30));

        txtDescuento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDescuento.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtDescuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescuentoActionPerformed(evt);
            }
        });
        panMain.add(txtDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 130, 30));

        txtSubtotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSubtotal.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtSubtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubtotalActionPerformed(evt);
            }
        });
        panMain.add(txtSubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 130, 30));

        txtIva.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtIva.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtIva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIvaActionPerformed(evt);
            }
        });
        panMain.add(txtIva, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 440, 130, 30));

        tabProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cant.", "Nombre", "Precio", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabProductos);

        panMain.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 460, 150));

        btnBuscar.setBackground(new java.awt.Color(11, 58, 82));
        btnBuscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar");
        btnBuscar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        panMain.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 60, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panMain, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRazonSocialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRazonSocialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRazonSocialActionPerformed

    private void txtIdProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdProveedorActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProductoActionPerformed
        
        formRegistroDetalleEntradaAdd formAgregar = new formRegistroDetalleEntradaAdd();
        formAgregar.setVisible(true);
        
    }//GEN-LAST:event_btnAgregarProductoActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtDescuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescuentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescuentoActionPerformed

    private void txtSubtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubtotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSubtotalActionPerformed

    private void txtIvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIvaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIvaActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        
        
        formBuscarProveedor formProv = new formBuscarProveedor();
        formProv.setVisible(true);
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formRegistroEntradaAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formRegistroEntradaAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formRegistroEntradaAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formRegistroEntradaAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formRegistroEntradaAdd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarProducto;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labCategoria;
    private javax.swing.JLabel labCodigo;
    private javax.swing.JLabel labDescripcion;
    private javax.swing.JLabel labMedida;
    private javax.swing.JLabel labPorcentajeIva;
    private javax.swing.JLabel labPrecio;
    private javax.swing.JLabel labRUC;
    private javax.swing.JLabel labRazonSocial;
    private javax.swing.JLabel labTitle;
    private javax.swing.JPanel panMain;
    private javax.swing.JTable tabProductos;
    private javax.swing.JTextField txtDescuento;
    private javax.swing.JFormattedTextField txtFechaIngreso;
    public static javax.swing.JTextField txtIdProveedor;
    private javax.swing.JTextField txtIva;
    public static javax.swing.JTextField txtRazonSocial;
    private javax.swing.JTextField txtSubtotal;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
